// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeQHjTUrQ5XkcZ-S_4nWYzd3BIqV3z_rQ',
    appId: '1:379856876454:web:2ddc312f2ee1442d8f5567',
    messagingSenderId: '379856876454',
    projectId: 'shifamangementapp',
    authDomain: 'shifamangementapp.firebaseapp.com',
    storageBucket: 'shifamangementapp.firebasestorage.app',
    measurementId: 'G-ES6YJRTJYJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhoxRdnwGmslzfdHfGt0o7NmgI9z0xYWQ',
    appId: '1:379856876454:android:ed089fbe81429bf68f5567',
    messagingSenderId: '379856876454',
    projectId: 'shifamangementapp',
    storageBucket: 'shifamangementapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsD___d7IoveLUghJsZanIb1UQUXOwK94',
    appId: '1:379856876454:ios:0a09eb9bd09d6f578f5567',
    messagingSenderId: '379856876454',
    projectId: 'shifamangementapp',
    storageBucket: 'shifamangementapp.firebasestorage.app',
    iosBundleId: 'com.shifa.shifaManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsD___d7IoveLUghJsZanIb1UQUXOwK94',
    appId: '1:379856876454:ios:0a09eb9bd09d6f578f5567',
    messagingSenderId: '379856876454',
    projectId: 'shifamangementapp',
    storageBucket: 'shifamangementapp.firebasestorage.app',
    iosBundleId: 'com.shifa.shifaManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeQHjTUrQ5XkcZ-S_4nWYzd3BIqV3z_rQ',
    appId: '1:379856876454:web:160374acee2a96278f5567',
    messagingSenderId: '379856876454',
    projectId: 'shifamangementapp',
    authDomain: 'shifamangementapp.firebaseapp.com',
    storageBucket: 'shifamangementapp.firebasestorage.app',
    measurementId: 'G-GRS46B3T04',
  );
}
